create type "public"."user_role" as enum ('customer', 'staff', 'admin');


  create table "public"."banner" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "image" text not null
      );


alter table "public"."banner" enable row level security;


  create table "public"."cart" (
    "id" bigint generated by default as identity not null,
    "added_at" timestamp with time zone not null default now(),
    "product_id" bigint,
    "quantity" smallint,
    "user_id" uuid
      );


alter table "public"."cart" enable row level security;


  create table "public"."category" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "image" text not null
      );


alter table "public"."category" enable row level security;


  create table "public"."favorite" (
    "id" bigint generated by default as identity not null,
    "added_at" timestamp with time zone not null default now(),
    "product_id" bigint,
    "user_id" uuid default gen_random_uuid()
      );


alter table "public"."favorite" enable row level security;


  create table "public"."image" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "product_id" bigint not null,
    "position" smallint default '1'::smallint,
    "image_url" text not null
      );


alter table "public"."image" enable row level security;


  create table "public"."notifications" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default gen_random_uuid(),
    "title" text,
    "body" text
      );


alter table "public"."notifications" enable row level security;


  create table "public"."order_item" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint,
    "quantity" smallint,
    "order_id" bigint
      );


alter table "public"."order_item" enable row level security;


  create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "total" numeric,
    "currency" text,
    "shipping" numeric
      );


alter table "public"."orders" enable row level security;


  create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text not null,
    "price" numeric not null,
    "category_id" bigint not null default '0'::bigint
      );


alter table "public"."products" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "user_role" public.user_role default 'customer'::public.user_role,
    "full_name" text,
    "avatar" text,
    "fcm_token" text
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX "Products_pkey" ON public.products USING btree (id);

CREATE UNIQUE INDEX banner_pkey ON public.banner USING btree (id);

CREATE UNIQUE INDEX cart_pkey ON public.cart USING btree (id);

CREATE UNIQUE INDEX category_pkey ON public.category USING btree (id);

CREATE UNIQUE INDEX favorite_pkey ON public.favorite USING btree (id);

CREATE UNIQUE INDEX image_pkey ON public.image USING btree (id);

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

CREATE UNIQUE INDEX order_item_pkey ON public.order_item USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX products_id_key ON public.products USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."banner" add constraint "banner_pkey" PRIMARY KEY using index "banner_pkey";

alter table "public"."cart" add constraint "cart_pkey" PRIMARY KEY using index "cart_pkey";

alter table "public"."category" add constraint "category_pkey" PRIMARY KEY using index "category_pkey";

alter table "public"."favorite" add constraint "favorite_pkey" PRIMARY KEY using index "favorite_pkey";

alter table "public"."image" add constraint "image_pkey" PRIMARY KEY using index "image_pkey";

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."order_item" add constraint "order_item_pkey" PRIMARY KEY using index "order_item_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."products" add constraint "Products_pkey" PRIMARY KEY using index "Products_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."cart" add constraint "cart_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cart" validate constraint "cart_product_id_fkey";

alter table "public"."cart" add constraint "cart_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."cart" validate constraint "cart_user_id_fkey1";

alter table "public"."favorite" add constraint "favorite_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."favorite" validate constraint "favorite_product_id_fkey";

alter table "public"."favorite" add constraint "favorite_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."favorite" validate constraint "favorite_user_id_fkey1";

alter table "public"."image" add constraint "image_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."image" validate constraint "image_product_id_fkey";

alter table "public"."notifications" add constraint "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."notifications" validate constraint "notifications_user_id_fkey";

alter table "public"."order_item" add constraint "order_item_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."order_item" validate constraint "order_item_order_id_fkey";

alter table "public"."order_item" add constraint "order_item_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.products(id) not valid;

alter table "public"."order_item" validate constraint "order_item_product_id_fkey";

alter table "public"."orders" add constraint "orders_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."orders" validate constraint "orders_user_id_fkey1";

alter table "public"."products" add constraint "Products_price_check" CHECK ((price > (0)::numeric)) not valid;

alter table "public"."products" validate constraint "Products_price_check";

alter table "public"."products" add constraint "products_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."products" validate constraint "products_category_id_fkey";

alter table "public"."products" add constraint "products_id_key" UNIQUE using index "products_id_key";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_profile_for_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, full_name, avatar, user_role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'avatar_url', ''),
    'customer'
  )
  on conflict (id) do nothing;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid()) and p.user_role = 'admin'
  );
$function$
;

grant delete on table "public"."banner" to "anon";

grant insert on table "public"."banner" to "anon";

grant references on table "public"."banner" to "anon";

grant select on table "public"."banner" to "anon";

grant trigger on table "public"."banner" to "anon";

grant truncate on table "public"."banner" to "anon";

grant update on table "public"."banner" to "anon";

grant delete on table "public"."banner" to "authenticated";

grant insert on table "public"."banner" to "authenticated";

grant references on table "public"."banner" to "authenticated";

grant select on table "public"."banner" to "authenticated";

grant trigger on table "public"."banner" to "authenticated";

grant truncate on table "public"."banner" to "authenticated";

grant update on table "public"."banner" to "authenticated";

grant delete on table "public"."banner" to "service_role";

grant insert on table "public"."banner" to "service_role";

grant references on table "public"."banner" to "service_role";

grant select on table "public"."banner" to "service_role";

grant trigger on table "public"."banner" to "service_role";

grant truncate on table "public"."banner" to "service_role";

grant update on table "public"."banner" to "service_role";

grant delete on table "public"."cart" to "anon";

grant insert on table "public"."cart" to "anon";

grant references on table "public"."cart" to "anon";

grant select on table "public"."cart" to "anon";

grant trigger on table "public"."cart" to "anon";

grant truncate on table "public"."cart" to "anon";

grant update on table "public"."cart" to "anon";

grant delete on table "public"."cart" to "authenticated";

grant insert on table "public"."cart" to "authenticated";

grant references on table "public"."cart" to "authenticated";

grant select on table "public"."cart" to "authenticated";

grant trigger on table "public"."cart" to "authenticated";

grant truncate on table "public"."cart" to "authenticated";

grant update on table "public"."cart" to "authenticated";

grant delete on table "public"."cart" to "service_role";

grant insert on table "public"."cart" to "service_role";

grant references on table "public"."cart" to "service_role";

grant select on table "public"."cart" to "service_role";

grant trigger on table "public"."cart" to "service_role";

grant truncate on table "public"."cart" to "service_role";

grant update on table "public"."cart" to "service_role";

grant delete on table "public"."category" to "anon";

grant insert on table "public"."category" to "anon";

grant references on table "public"."category" to "anon";

grant select on table "public"."category" to "anon";

grant trigger on table "public"."category" to "anon";

grant truncate on table "public"."category" to "anon";

grant update on table "public"."category" to "anon";

grant delete on table "public"."category" to "authenticated";

grant insert on table "public"."category" to "authenticated";

grant references on table "public"."category" to "authenticated";

grant select on table "public"."category" to "authenticated";

grant trigger on table "public"."category" to "authenticated";

grant truncate on table "public"."category" to "authenticated";

grant update on table "public"."category" to "authenticated";

grant delete on table "public"."category" to "service_role";

grant insert on table "public"."category" to "service_role";

grant references on table "public"."category" to "service_role";

grant select on table "public"."category" to "service_role";

grant trigger on table "public"."category" to "service_role";

grant truncate on table "public"."category" to "service_role";

grant update on table "public"."category" to "service_role";

grant delete on table "public"."favorite" to "anon";

grant insert on table "public"."favorite" to "anon";

grant references on table "public"."favorite" to "anon";

grant select on table "public"."favorite" to "anon";

grant trigger on table "public"."favorite" to "anon";

grant truncate on table "public"."favorite" to "anon";

grant update on table "public"."favorite" to "anon";

grant delete on table "public"."favorite" to "authenticated";

grant insert on table "public"."favorite" to "authenticated";

grant references on table "public"."favorite" to "authenticated";

grant select on table "public"."favorite" to "authenticated";

grant trigger on table "public"."favorite" to "authenticated";

grant truncate on table "public"."favorite" to "authenticated";

grant update on table "public"."favorite" to "authenticated";

grant delete on table "public"."favorite" to "service_role";

grant insert on table "public"."favorite" to "service_role";

grant references on table "public"."favorite" to "service_role";

grant select on table "public"."favorite" to "service_role";

grant trigger on table "public"."favorite" to "service_role";

grant truncate on table "public"."favorite" to "service_role";

grant update on table "public"."favorite" to "service_role";

grant delete on table "public"."image" to "anon";

grant insert on table "public"."image" to "anon";

grant references on table "public"."image" to "anon";

grant select on table "public"."image" to "anon";

grant trigger on table "public"."image" to "anon";

grant truncate on table "public"."image" to "anon";

grant update on table "public"."image" to "anon";

grant delete on table "public"."image" to "authenticated";

grant insert on table "public"."image" to "authenticated";

grant references on table "public"."image" to "authenticated";

grant select on table "public"."image" to "authenticated";

grant trigger on table "public"."image" to "authenticated";

grant truncate on table "public"."image" to "authenticated";

grant update on table "public"."image" to "authenticated";

grant delete on table "public"."image" to "service_role";

grant insert on table "public"."image" to "service_role";

grant references on table "public"."image" to "service_role";

grant select on table "public"."image" to "service_role";

grant trigger on table "public"."image" to "service_role";

grant truncate on table "public"."image" to "service_role";

grant update on table "public"."image" to "service_role";

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";

grant delete on table "public"."order_item" to "anon";

grant insert on table "public"."order_item" to "anon";

grant references on table "public"."order_item" to "anon";

grant select on table "public"."order_item" to "anon";

grant trigger on table "public"."order_item" to "anon";

grant truncate on table "public"."order_item" to "anon";

grant update on table "public"."order_item" to "anon";

grant delete on table "public"."order_item" to "authenticated";

grant insert on table "public"."order_item" to "authenticated";

grant references on table "public"."order_item" to "authenticated";

grant select on table "public"."order_item" to "authenticated";

grant trigger on table "public"."order_item" to "authenticated";

grant truncate on table "public"."order_item" to "authenticated";

grant update on table "public"."order_item" to "authenticated";

grant delete on table "public"."order_item" to "service_role";

grant insert on table "public"."order_item" to "service_role";

grant references on table "public"."order_item" to "service_role";

grant select on table "public"."order_item" to "service_role";

grant trigger on table "public"."order_item" to "service_role";

grant truncate on table "public"."order_item" to "service_role";

grant update on table "public"."order_item" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "banner"
  on "public"."banner"
  as permissive
  for all
  to public
using (true);



  create policy "cart"
  on "public"."cart"
  as permissive
  for all
  to public
using (true);



  create policy "category"
  on "public"."category"
  as permissive
  for all
  to public
using (true);



  create policy "favorite"
  on "public"."favorite"
  as permissive
  for all
  to public
using (true);



  create policy "image"
  on "public"."image"
  as permissive
  for all
  to public
using (true);



  create policy "Enable delete for users based on user_id"
  on "public"."notifications"
  as permissive
  for delete
  to public
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."notifications"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."notifications"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."order_item"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for users based on user_id"
  on "public"."orders"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable users to view their own data only"
  on "public"."orders"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for authenticated"
  on "public"."products"
  as permissive
  for select
  to authenticated
using (true);



  create policy "insert own profile"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "select own or admin"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using (((( SELECT auth.uid() AS uid) = id) OR public.is_admin()));



  create policy "update own or admin"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using (((( SELECT auth.uid() AS uid) = id) OR public.is_admin()))
with check (((( SELECT auth.uid() AS uid) = id) OR public.is_admin()));


CREATE TRIGGER "notifications-webhook" AFTER INSERT ON public.notifications FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://qxcrdbpinosdfcmtsnom.supabase.co/functions/v1/notifications', 'POST', '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4Y3JkYnBpbm9zZGZjbXRzbm9tIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTcxMzI0OCwiZXhwIjoyMDc1Mjg5MjQ4fQ.co3r0FL3E6EF_SihgxSMdh_HFcZN8MZjP8yhwuLEFEA"}', '{}', '1000');

CREATE TRIGGER create_profile_on_signup AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_profile_for_new_user();


